# This is a basic workflow to help you get started with Actions

name: Second | Powershell echo

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug

runs-on: windows-latest

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_and_release:
    steps:
    - name: Print Inputs
      run: |
        echo "Log level: ${{ github.event.inputs.logLevel }}"
        echo "branch name: ${{ github.ref_name }}"
    
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Run Build action
      uses: ./.github/workflows/build.yml

    - name: Checkoutput
      run: .\Scripts\release.ps1
