# This is a basic workflow to help you get started with Actions

name: First | Powershell echo

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  print & Inputs:
    runs-on: ubuntu-latest
    steps:
    - name: Print Inputs
      run: |
        echo "Log level: ${{ github.event.inputs.logLevel }}"
        echo "branch name: ${{ github.ref_name }}"
